# Defines a list of files that are part of main core  
# Changes to these files/filters define how our CI test suite is ran.
core: &core
  - vadimdor/*.py
  - vadimdor/package_constraints.txt
  - pyproject.toml
  - requirements.txt
  - setup.cfg


# Testing related files that affect the whole test/linting suite
tests: &tests
  - codecov.yaml
  - pylint/**
  - requirements_test_pre_commit.txt
  - requirements_test.txt
  - tests/auth/**

other: &other
  - .github/workflows/**
  - vadimdor/scripts/**

requirements: &requirements
  - .github/workflows/**
  - vadimdor/package_constraints.txt
  - script/pip_check
  - requirements*.txt
  - setup.cfg

any:
  - *core
  - *other
  - *requirements
  - *tests
