name: python-isort
#  [push]            branch: ${{ github.ref }}
on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: isort/isort-action@master
        with:
            configuration: " --verbose --check-only   --diff  --show-files "
           # requirementsFiles: "requirements.txt requirements-test.txt" --show-config
          