name: Ruff Linter Formatter
#  [push]            branch: ${{ github.ref }}
on:
    workflow_dispatch:
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1