name: Python linter Pylint
#[push]
on: 
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: ["3.8", "3.9", "3.10"]
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint==v3.0.0a6 && pylint --version --list-msgs-enabled
        pip install --upgrade pip
        pip install \
        pylint-per-file-ignores \
        code_style \
        emptystring \
        comparetozero \
        confusing_elif \
        consider_ternary_expression \
        bad_builtin \
        mccabe \
        docstyle \
        check_elif \
        redefined_variable_type \
        overlapping_exceptions \
        docparams \
        empty_comment \
        set_membership \
        typing \
        while_used
        #         broad_try_clause \
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`

