---
name: YAML Lint

on:
  # push:
 #   paths:
  #    - '**.yml'
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ibiqlik/action-yamllint@v3.1
        with:
          config_file: configs/.yamllint.yml
          strict: false
